export enum ItemType {
    MINIFIG = "MINIFIG",
    PART = "PART",
    SET = "SET",
    BOOK = "BOOK",
    GEAR = "CATALOG",
    INSTRUCTION = "INSTRUCTION",
    UNSORTED_LOT = "UNSORTED_LOT",
    ORIGINAL_BOX = "ORIGINAL_BOX",
}